feat: commitzen and lint-staged configured
commitzen to automate conventional commit pattern and lint-staged to improve perfomamnce when
linting code

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,17 +3,10 @@
 
 echo '🏗️👷 Formatting, styling and building your project before committing changes'
 
-npm run lint:fix ||
+npx lint-staged ||
 (
-  echo '😤🏀👋😤 ESLint Check Failed. 😤🏀👋😤
-    Make the required changes listed above, add changes and try to commit again.'
-  false;
-)
-
-npm run pretty ||
-(
-  echo '🤢🤮🤢🤮 Prettier Check Failed. 🤢🤮🤢🤮
-    Run npm run format, add changes and try commit again.';
+  echo '🤢🤮🤢🤮 Linters Check Failed. 🤢🤮🤢🤮
+    Run npm run lint or npm run pretty to check what went wrong.';
   false;
 )
 
